// Golden-bytes parity for `application/x-sfm-points-v1` (lean-audit
// item 5.3). Loads the server-owned committed fixture
// (generated by sfmapi/server/schemas/points_binary.py and asserted
// byte-identical to that encoder by the core repo's
// tests/contract/test_f_golden_points_parity.py) and asserts the
// generated TS parser decodes the exact same values the Python legs
// assert. The expected table is hardcoded here so the test stays
// self-contained; it skips when the sibling core checkout (or the
// SFMAPI_GOLDEN_POINTS_FIXTURE override) isn't present.
//
// Keep GOLDEN in lockstep with GOLDEN_ROWS / GOLDEN_BBOX_* in
// sfmapi/tests/contract/test_f_golden_points_parity.py.

import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import { parsePointsBinary } from "../src/_generated/client.js";

const fixturePath =
  process.env["SFMAPI_GOLDEN_POINTS_FIXTURE"] ??
  fileURLToPath(
    new URL(
      "../../../sfmapi/tests/contract/fixtures/golden_points_v1.bin",
      import.meta.url,
    ),
  );

// xyz / bbox travel as float32 — round the human-readable literals
// through Math.fround so expectations match the wire precision.
const f = Math.fround;

const GOLDEN = {
  bbox_min: [f(-16777216), f(-3.25), f(-0.5)],
  bbox_max: [f(1073741824), f(65536), f(2.75)],
  records: [
    { point3d_id: 0n, xyz: [0, 0, 0], rgb: [0, 0, 0], track_len: 0 },
    {
      point3d_id: 0xffffffffffffffffn,
      xyz: [f(1.5), f(-2.25), f(0.125)],
      rgb: [255, 255, 255],
      track_len: 65535,
    },
    {
      point3d_id: 42n,
      xyz: [f(1073741824), f(-16777216), f(65536)],
      rgb: [0, 128, 255],
      track_len: 7,
    },
    {
      point3d_id: 0xdeadbeefn,
      xyz: [f(0.1), f(-3.14159), f(2.71828)],
      rgb: [1, 2, 3],
      track_len: 1234,
    },
  ],
};

describe("golden-bytes parity: application/x-sfm-points-v1", () => {
  it.runIf(existsSync(fixturePath))(
    "parsePointsBinary decodes the server-encoded golden fixture exactly",
    () => {
      const raw = readFileSync(fixturePath);
      // Copy out of Node's pooled Buffer so the ArrayBuffer starts at 0.
      const buf = raw.buffer.slice(
        raw.byteOffset,
        raw.byteOffset + raw.byteLength,
      ) as ArrayBuffer;

      const out = parsePointsBinary(buf);
      expect(out.count).toBe(GOLDEN.records.length);
      expect(out.bbox_min).toEqual(GOLDEN.bbox_min);
      expect(out.bbox_max).toEqual(GOLDEN.bbox_max);
      expect(out.records).toHaveLength(GOLDEN.records.length);
      for (let i = 0; i < GOLDEN.records.length; i++) {
        const got = out.records[i]!;
        const want = GOLDEN.records[i]!;
        expect(got.point3d_id).toBe(want.point3d_id);
        expect(got.xyz).toEqual(want.xyz);
        expect(got.rgb).toEqual(want.rgb);
        expect(got.track_len).toBe(want.track_len);
      }
    },
  );
});
